# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'friend_map_ui.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1600, 494)
        MainWindow.setMinimumSize(QtCore.QSize(500, 100))
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        MainWindow.setToolTip("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.stackedWidget_main = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget_main.setObjectName("stackedWidget_main")
        self.page_main = QtWidgets.QWidget()
        self.page_main.setObjectName("page_main")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.page_main)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tableView_data = QtWidgets.QTableView(self.page_main)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableView_data.sizePolicy().hasHeightForWidth())
        self.tableView_data.setSizePolicy(sizePolicy)
        self.tableView_data.setEditTriggers(QtWidgets.QAbstractItemView.AnyKeyPressed|QtWidgets.QAbstractItemView.CurrentChanged|QtWidgets.QAbstractItemView.DoubleClicked|QtWidgets.QAbstractItemView.EditKeyPressed)
        self.tableView_data.setAlternatingRowColors(True)
        self.tableView_data.setSortingEnabled(True)
        self.tableView_data.setObjectName("tableView_data")
        self.gridLayout_2.addWidget(self.tableView_data, 0, 1, 12, 1)
        self.pushButton_save_map = QtWidgets.QPushButton(self.page_main)
        self.pushButton_save_map.setObjectName("pushButton_save_map")
        self.gridLayout_2.addWidget(self.pushButton_save_map, 7, 0, 1, 1)
        self.pushButton_save_map_as = QtWidgets.QPushButton(self.page_main)
        self.pushButton_save_map_as.setObjectName("pushButton_save_map_as")
        self.gridLayout_2.addWidget(self.pushButton_save_map_as, 8, 0, 1, 1)
        self.pushButton_save_data_as = QtWidgets.QPushButton(self.page_main)
        self.pushButton_save_data_as.setObjectName("pushButton_save_data_as")
        self.gridLayout_2.addWidget(self.pushButton_save_data_as, 5, 0, 1, 1)
        self.pushButton_import = QtWidgets.QPushButton(self.page_main)
        self.pushButton_import.setObjectName("pushButton_import")
        self.gridLayout_2.addWidget(self.pushButton_import, 3, 0, 1, 1)
        self.pushButton_remove_person = QtWidgets.QPushButton(self.page_main)
        self.pushButton_remove_person.setObjectName("pushButton_remove_person")
        self.gridLayout_2.addWidget(self.pushButton_remove_person, 2, 0, 1, 1)
        self.pushButton_add_person = QtWidgets.QPushButton(self.page_main)
        self.pushButton_add_person.setObjectName("pushButton_add_person")
        self.gridLayout_2.addWidget(self.pushButton_add_person, 0, 0, 1, 1)
        self.pushButton_show_map = QtWidgets.QPushButton(self.page_main)
        self.pushButton_show_map.setObjectName("pushButton_show_map")
        self.gridLayout_2.addWidget(self.pushButton_show_map, 6, 0, 1, 1)
        self.pushButton_save_data = QtWidgets.QPushButton(self.page_main)
        self.pushButton_save_data.setObjectName("pushButton_save_data")
        self.gridLayout_2.addWidget(self.pushButton_save_data, 4, 0, 1, 1)
        self.pushButton_add_row = QtWidgets.QPushButton(self.page_main)
        self.pushButton_add_row.setObjectName("pushButton_add_row")
        self.gridLayout_2.addWidget(self.pushButton_add_row, 1, 0, 1, 1)
        self.pushButton_set_home = QtWidgets.QPushButton(self.page_main)
        self.pushButton_set_home.setObjectName("pushButton_set_home")
        self.gridLayout_2.addWidget(self.pushButton_set_home, 9, 0, 1, 1)
        self.textEdit_output = QtWidgets.QTextEdit(self.page_main)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit_output.sizePolicy().hasHeightForWidth())
        self.textEdit_output.setSizePolicy(sizePolicy)
        self.textEdit_output.setObjectName("textEdit_output")
        self.gridLayout_2.addWidget(self.textEdit_output, 10, 0, 1, 1)
        self.stackedWidget_main.addWidget(self.page_main)
        self.page_map = QtWidgets.QWidget()
        self.page_map.setObjectName("page_map")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.page_map)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.graphicsView_map = QtWidgets.QGraphicsView(self.page_map)
        self.graphicsView_map.setObjectName("graphicsView_map")
        self.gridLayout_3.addWidget(self.graphicsView_map, 0, 1, 2, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem, 1, 0, 1, 1)
        self.pushButton_return_to_main = QtWidgets.QPushButton(self.page_map)
        self.pushButton_return_to_main.setObjectName("pushButton_return_to_main")
        self.gridLayout_3.addWidget(self.pushButton_return_to_main, 0, 0, 1, 1)
        self.stackedWidget_main.addWidget(self.page_map)
        self.gridLayout.addWidget(self.stackedWidget_main, 5, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1600, 17))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.stackedWidget_main.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Custom Protocol Creator"))
        self.pushButton_save_map.setText(_translate("MainWindow", "Save Map"))
        self.pushButton_save_map_as.setText(_translate("MainWindow", "Save Map As.."))
        self.pushButton_save_data_as.setText(_translate("MainWindow", "Export to Excel As..."))
        self.pushButton_import.setText(_translate("MainWindow", "Import From Excel"))
        self.pushButton_remove_person.setText(_translate("MainWindow", "Remove Selected Person"))
        self.pushButton_add_person.setText(_translate("MainWindow", "Add Person"))
        self.pushButton_show_map.setText(_translate("MainWindow", "Show Map"))
        self.pushButton_save_data.setText(_translate("MainWindow", "Export to Excel"))
        self.pushButton_add_row.setText(_translate("MainWindow", "Add Row"))
        self.pushButton_set_home.setText(_translate("MainWindow", "Set Home"))
        self.pushButton_return_to_main.setText(_translate("MainWindow", "Return"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))


